// <auto-generated />
using System;
using CheckFipe.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CheckFipe.Migrations
{
    [DbContext(typeof(CheckFipeContext))]
    [Migration("20191007022744_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CheckFipe.Entities.ConsultaVeiculo", b =>
                {
                    b.Property<long>("IdConsultaVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataConsultaVeiculo")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdVeiculo")
                        .HasColumnType("bigint");

                    b.HasKey("IdConsultaVeiculo");

                    b.HasIndex("IdVeiculo");

                    b.ToTable("ConsultaVeiculo");
                });

            modelBuilder.Entity("CheckFipe.Entities.Veiculo", b =>
                {
                    b.Property<long>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnoModelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoAno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoFipe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CodigoMarca")
                        .HasColumnType("bigint");

                    b.Property<string>("DescricaoCombustivel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoMarca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoModelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Preco")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVeiculo");

                    b.ToTable("Veiculo");
                });

            modelBuilder.Entity("CheckFipe.Entities.ConsultaVeiculo", b =>
                {
                    b.HasOne("CheckFipe.Entities.Veiculo", "Veiculo")
                        .WithMany("ConsultasVeiculo")
                        .HasForeignKey("IdVeiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
